[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build"]
dependsOn = ["install"]

[start]
cmd = "pnpm run preview"

[variables]
NIXPACKS_NO_COPY = "true"
